/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tvCsy6olv6M
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function ItemDetails() {
  return (
    <div key="1" className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl px-4 mx-auto py-6">
      <div>
        <Carousel className="rounded-lg overflow-hidden">
          <CarouselContent>
            <CarouselItem>
              <img
                alt="Product Image"
                className="object-cover w-full aspect-square"
                height={600}
                src="/placeholder.svg"
                width={600}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                alt="Product Image"
                className="object-cover w-full aspect-square"
                height={600}
                src="/placeholder.svg"
                width={600}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                alt="Product Image"
                className="object-cover w-full aspect-square"
                height={600}
                src="/placeholder.svg"
                width={600}
              />
            </CarouselItem>
          </CarouselContent>
          <div className="flex justify-between absolute top-1/2 left-0 right-0 -translate-y-1/2 px-4">
            <CarouselPrevious className="bg-white/50 dark:bg-gray-900/50 rounded-full p-2 hover:bg-white/80 dark:hover:bg-gray-900/80 transition-colors">
              <ArrowLeftIcon className="w-6 h-6 text-gray-900 dark:text-gray-50" />
            </CarouselPrevious>
            <CarouselNext className="bg-white/50 dark:bg-gray-900/50 rounded-full p-2 hover:bg-white/80 dark:hover:bg-gray-900/80 transition-colors">
              <ArrowRightIcon className="w-6 h-6 text-gray-900 dark:text-gray-50" />
            </CarouselNext>
          </div>
        </Carousel>
      </div>
      <div className="grid gap-4 md:gap-8">
        <div className="flex items-center gap-4">
          <UserIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
          <span className="font-medium">Jane Doe</span>
        </div>
        <div>
          <h1 className="text-2xl md:text-3xl font-bold">Vintage Leather Satchel</h1>
          <p className="text-gray-500 dark:text-gray-400 text-sm">
            A timeless and durable leather satchel perfect for everyday use.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-3xl font-bold">$99</span>
          <span className="text-gray-500 line-through">$149</span>
        </div>
        <div className="text-sm text-gray-500 dark:text-gray-400">Listed on May 29, 2024</div>
        <div className="flex items-center gap-4">
          <Button className="w-full">Chat with Seller</Button>
          <div className="flex items-center gap-2">
            <Button>Place Bid</Button>
            <Input className="w-24" type="number" />
          </div>
        </div>
        <div className="border rounded-lg overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>User</TableHead>
                <TableHead>Bid</TableHead>
                <TableHead>Date/Time</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>John Doe</TableCell>
                <TableCell>$120</TableCell>
                <TableCell>May 29, 2024 10:30 AM</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Jane Smith</TableCell>
                <TableCell>$130</TableCell>
                <TableCell>May 29, 2024 11:15 AM</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Michael Johnson</TableCell>
                <TableCell>$115</TableCell>
                <TableCell>May 29, 2024 1:45 PM</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  )
}

function ArrowLeftIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function ArrowRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
